version: '3.9'
services:
  postgres:
    image: ankane/pgvector:v0.5.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ragdb
      - PGPASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -U postgres -d ragdb"
      interval: 2s
      timeout: 20s
      retries: 10
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11431:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    volumes:
      - ./ollama:/root/.ollama
#  ollama:
#    image: dustynv/ollama:r36.4-cu129-24.04
#    container_name: ollama
#    runtime: nvidia
#    ports:
#      - "11431:11434"
#    volumes:
#      - ./ollama:/ollama
#    environment:
#      - OLLAMA_MODELS=/ollama
#    restart: unless-stopped
